// src/app/components/search-box/option/option.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  Input,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import { DisplayData } from 'src/app/types';

@Component({
  selector: 'li[app-option]',
  templateUrl: './option.component.html',
  styleUrls: ['./option.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OptionComponent<T extends DisplayData> implements OnChanges {
  @Input() data?: T;
  @Input() selected?: boolean;

  initials = ``;

  ngOnChanges(changes: SimpleChanges): void {
    if (`data` in changes && changes['data'].currentValue) {
      const { firstName, lastName }: T = changes['data'].currentValue;
      const firstNameInitial = firstName.charAt(0);
      const lastNameInitial = lastName.charAt(0);
      this.initials = `${firstNameInitial}${lastNameInitial}`.toUpperCase();
    }
  }
}

<ng-container *ngIf="data; else emptyOption">
  <div class="initials">{{ initials }}</div>
  <div>
    <div class="name">{{ data.name }}</div>
    <div class="email color-muted">{{ data.email }}</div>
  </div>
</ng-container>
<ng-template #emptyOption>
  <span class="color-muted">
    <ng-content></ng-content>
  </span>
</ng-template>

// src/components/SearchBox/Option/index.tsx
import React from 'react';
import { DisplayData } from '../../../types';
import './index.scss';

const Option_PureFunction = ({
  data,
  selected,
  children,
}: React.PropsWithChildren<{ data?: DisplayData; selected?: boolean }>) => {
  // list empty option
  if (!data) {
    return <li className="color-muted">{children}</li>;
  }

  const initials = `${data.firstName.charAt(0)}${data.lastName.charAt(0)}`.toUpperCase();

  // valid list option
  return (
    <li key={data.id} role="option" aria-label={data.name} aria-selected={selected}>
      <div className="initials">{initials}</div>
      <div>
        <div className="name">{data.name}</div>
        <div className="email color-muted">{data.email}</div>
      </div>
    </li>
  );
};

export const Option = React.memo(Option_PureFunction);
