// src/App.tsx
import React from 'react';
import './App.scss';
import { useFetchManagerData } from './services';
import { SearchBox } from './components';

const API_URL = `https://gist.githubusercontent.com/daviferreira/41238222ac31fe36348544ee1d4a9a5e/raw/5dc996407f6c9a6630bfcec56eee22d4bc54b518/employees.json`;

const App = () => {
  const { data, loading, error } = useFetchManagerData(API_URL);

  return loading ? (
    <div>Loading...</div>
  ) : (
    <main>
      <SearchBox list={data} placeholder="Choose Manager" listAriaLabel="Manager List"></SearchBox>
      {error && <div className="error">{error}</div>}
    </main>
  );
};

export default App;

// src/app/app.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

const API_URL = `https://gist.githubusercontent.com/daviferreira/41238222ac31fe36348544ee1d4a9a5e/raw/5dc996407f6c9a6630bfcec56eee22d4bc54b518/employees.json`;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {}

<ng-container *ngIf="data$ | async as obs; else loading">
  <app-search-box
    [list]="obs.data"
    placeholder="Choose Manager"
    listAriaLabel="Manager List"
  ></app-search-box>
  <div class="error" *ngIf="obs.error">{{ obs.error }}</div>
</ng-container>
<ng-template #loading>Loading...</ng-template>
